---

  - name: Configure sshd
    lineinfile:
      path: "/etc/ssh/sshd_config"
      regex: "^(#)?{{item.key}}"
      line: "{{item.key}} {{item.value}}"
      state: present
    loop:
      - { key: "ClientAliveInterval", value: 1200 }
      - { key: "ClientAliveCountMax", value: 6 }
      - { key: "PrintLastLog", value: "no" }
      - { key: "Port", value: "{{ ssh_port }}" }
      - { key: "PermitRootLogin", value: "no" }
      - { key: "X11Forwarding", value: "yes" }
      - { key: "PermitEmptyPasswords", value: "no" }
      - { key: "PasswordAuthentication", value: "no" }      
    notify:
      - restart ssh
    tags:
      - ssh

  - name: Install Fail2ban
    yum:
      name: fail2ban
      state: present
    when: ansible_os_family == "RedHat"

  - name: Install Fail2ban
    apt:
      name: fail2ban
      state: present
      update_cache: yes
    when: ansible_os_family == "Debian"

  - name: Configure Fail2ban
    template:
      src: fail2ban.j2
      dest: /etc/fail2ban/jail.local
    notify:
      - restart fail2ban
    tags:
      - ssh

  - name: Enable Fail2ban
    service:
      name: fail2ban
      state: started
      enabled: yes
    tags:
      - ssh

  - name: SSH CentOS
    include_tasks: centos.yaml
    when: ansible_os_family == "RedHat"

  - name: SSH Ubuntu
    include_tasks: ubuntu.yaml
    when: ansible_os_family == "Debian"