---

  - name: Install ufw
    apt:
      package: ufw
      state: present
    tags:
      - ssh

  - name: Configure ufw defaults
    ufw:
      direction: "{{ item.direction }}"
      policy: "{{ item.policy }}"
    with_items:
      - { direction: 'incoming', policy: 'deny' }
      - { direction: 'outgoing', policy: 'allow' }
    notify:
      - restart ufw
    tags:
      - ssh

  - name: Configure ufw rules
    ufw:
      rule: "{{ item.rule }}"
      port: "{{ item.port }}"
      proto: "{{ item.proto }}"
    with_items:
      - { rule: 'limit', port: '{{ ssh_port }}', proto: 'tcp' }
      - { rule: 'allow', port: '{{ ssh_port }}', proto: 'tcp' }      
      - { rule: 'allow', port: '1194', proto: 'tcp' }
    notify:
      - restart ufw
    tags:
      - ssh

  - name: Enable ufw logging
    ufw:
      logging: on
    notify:
      - restart ufw
    tags:
      - ssh

  - name: Enable ufw
    ufw:
      state: enabled
    tags:
      - ssh