---

  - name: Container CentOS
    include_tasks: centos.yaml
    when: ansible_os_family == "RedHat"

  - name: Container Ubuntu
    include_tasks: ubuntu.yaml
    when: ansible_os_family == "Debian"

  - name: Install Docker compose
    get_url:
      url : https://github.com/docker/compose/releases/download/{{ compose_version }}/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 0755

  - name: Install Docker module
    pip:
      name: docker
      executable: pip3
      state: latest

  - name: Start and Enable Docker service
    service:
      name: docker
      state: started
      enabled: yes

  - name: Add user to docker group
    user:
      name: "{{ vpn_user }}"
      groups: docker
      append: yes

  - name: Validate container creation
    docker_container:
      name: test
      state: present
      image: busybox
      command: sleep 10s
      cleanup: yes
      detach: no