---

  - name: Base CentOS
    include_tasks: centos.yaml
    when: ansible_os_family == "RedHat"
    tags:
      - base

  - name: Base Ubuntu
    include_tasks: ubuntu.yaml
    when: ansible_os_family == "Debian"
    tags:
      - base

  - name: Set hostname
    hostname:
      name: "vm-{{ my_spec }}"
    tags:
      - base

  - name: Set timezone
    timezone:
      name: "{{ tz }}"
    tags:
      - base

  - name: Set PS1
    lineinfile:
      path: "/etc/profile.d/{{ my_spec }}.sh"
      line: export PS1="({{ my_spec | upper }}) [\t] \u@\h:\w \\$ \[$(tput sgr0)\]"
      create: yes
      owner: root
      group: root
      mode: 0644
      validate: /bin/bash -n %s
    tags:
      - base

  - name: Create user
    user:
      name: "{{ my_user }}"
      comment: "{{ my_spec | upper }}"
      uid: 222
      shell: /bin/bash
      create_home: True
      home: "/home/{{ my_user }}"
    register: created_user
    tags:
      - base

  - name: Create password
    shell: /usr/bin/openssl rand -base64 32
    register: my_pass
    when: created_user.changed
    tags:
      - base

  - name: Define password
    shell: echo {{ my_user }}:{{ my_pass.stdout }} | chpasswd
    when: created_user.changed
    tags:
      - base

  - name: Details of {{ my_user }} user
    debug: msg="Password for {{ my_user }} is {{ my_pass.stdout }}"
    when: created_user.changed
    tags:
      - base

  - name: Create ~{{ my_user }}/.ssh folder
    file:
      path: "~{{ my_user }}/.ssh"
      state: directory
      owner: "{{ my_user }}"
      group: "{{ my_user }}"
      mode: 0700
    tags:
      - base

  - name: Upload Pub key
    copy:
      src: "{{ ssh_pubkey }}"
      dest: ~{{ my_user }}/.ssh/authorized_keys
      owner: "{{ my_user }}"
      group: "{{ my_user }}"
      mode: 0700
    tags:
      - base