---

  - name: Install basic packages
    apt:
      update_cache: yes
      pkg:
      - git
      - htop
      - zip
      - wget
      - dos2unix
      - vim
      - lsof
      - net-tools
      - jq
      - python3
      - python3-pip