---

- hosts: all
  gather_facts: yes
  become: yes

  vars:
    my_user: ukn
    my_spec: vpn
    ssh_pubkey: ~/.ssh/id_rsa.pub
    
  roles:
    - role: base
    - role: ssh
    - role: container
    - role: vpn